require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.6

Rails:
  Enabled: true

Layout/LineLength:
  Max: 160

Style/FrozenStringLiteralComment:
  Enabled: false

# Crying, but pragmatic
Style/Documentation:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'

RSpec/NestedGroups:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

