development:
  :concurrency: 5
  :queues:
    - CHANGEME_PROJECT_CODENAME_development_default
    - CHANGEME_PROJECT_CODENAME_development_mailers
production:
  :concurrency: 5
  :queues:
    - default
    - CHANGEME_PROJECT_CODENAME_production_default
    - CHANGEME_PROJECT_CODENAME_production_mailers
